//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRPGRUPO
    {
        public int TENANT_ID { get; set; }
        public long IDCRPGRUPO { get; set; }
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<bool> ISGRUPOFINAL { get; set; }
        public Nullable<int> NUMERONIVEL { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_CATALOGO { get; set; }
    }
}
