//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_ENDERECO
    {
        public string ID_ENDERECO { get; set; }
        public string PESSOA_ID { get; set; }
        public string LOGRADOURO { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string TIPOENDERECO_CD { get; set; }
        public bool IS_PRINCIPAL { get; set; }
    
        public virtual EST_PESSOA EST_PESSOA { get; set; }
        public virtual EST_TIPOENDERECO EST_TIPOENDERECO { get; set; }
        public virtual EST_UF EST_UF { get; set; }
    }
}
