//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_PESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_PESSOA()
        {
            this.EST_CONTATO = new HashSet<EST_CONTATO>();
            this.EST_ENDERECO = new HashSet<EST_ENDERECO>();
            this.EST_LANCAMENTO = new HashSet<EST_LANCAMENTO>();
            this.EST_LANCAMENTO1 = new HashSet<EST_LANCAMENTO>();
            this.EST_LANCAMENTO2 = new HashSet<EST_LANCAMENTO>();
        }
    
        public long TENANT_ID { get; set; }
        public string ID_PESSOA { get; set; }
        public string TX_NOMEPESSOA { get; set; }
        public string TIPOPESSOA_CD { get; set; }
        public string PAPEL_CD { get; set; }
        public string TX_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public Nullable<System.DateTime> DT_FUNDACAO { get; set; }
        public System.DateTime DT_INICIOVINCULO { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public Nullable<System.DateTime> DT_ULTIMAALTERACAO { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public bool IS_ESTRANGEIRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_CONTATO> EST_CONTATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ENDERECO> EST_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LANCAMENTO> EST_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LANCAMENTO> EST_LANCAMENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LANCAMENTO> EST_LANCAMENTO2 { get; set; }
        public virtual EST_PAPEL EST_PAPEL { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
        public virtual EST_TIPOPESSOA EST_TIPOPESSOA { get; set; }
    }
}
