//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_ANEXO_LANCAMENTO
    {
        public long TENANT_ID { get; set; }
        public long ID_ANEXO { get; set; }
        public long LANCAMENTOID { get; set; }
        public string NOMEARQUIVO { get; set; }
        public byte[] ARQUIVO { get; set; }
        public string COMENTARIO { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public string USUARIOID { get; set; }
        public bool IS_NFE { get; set; }
    
        public virtual EST_LANCAMENTO EST_LANCAMENTO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
        public virtual INFRAUSUARIO INFRAUSUARIO { get; set; }
    }
}
