//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_TIPOENDERECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_TIPOENDERECO()
        {
            this.EST_ENDERECO = new HashSet<EST_ENDERECO>();
        }
    
        public string CD_TIPOENDERECO { get; set; }
        public string TX_TIPOENDERECO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ENDERECO> EST_ENDERECO { get; set; }
    }
}
