//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_PRODUTO()
        {
            this.EST_HISTORICO_PRECO = new HashSet<EST_HISTORICO_PRECO>();
            this.EST_PRODUTO_LANCTO = new HashSet<EST_PRODUTO_LANCTO>();
        }
    
        public long TENANT_ID { get; set; }
        public string ID_PRODUTO { get; set; }
        public string TX_NOME { get; set; }
        public string TX_DESCRICAO { get; set; }
        public string CATEGORIA_CD { get; set; }
        public Nullable<long> QT_MINIMA { get; set; }
        public Nullable<long> QT_ATUAL { get; set; }
        public Nullable<decimal> VL_PRECO_RECOMENDADO { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual EST_CATEGORIAPRODUTO EST_CATEGORIAPRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_HISTORICO_PRECO> EST_HISTORICO_PRECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_PRODUTO_LANCTO> EST_PRODUTO_LANCTO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
    }
}
