//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_LOG_AUDITORIA
    {
        public long TENANT_ID { get; set; }
        public long ID_LOG { get; set; }
        public string TX_TABELA { get; set; }
        public string TX_ACAOREALIZADA { get; set; }
        public System.DateTime DT_ACAOREALIZADA { get; set; }
        public string TX_DESCRICAODETALHADA { get; set; }
        public string INFRAUSUARIO_ID { get; set; }
    
        public virtual INFRAUSUARIO INFRAUSUARIO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
    }
}
