//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_HISTORICO_PRECO
    {
        public long TENANT_ID { get; set; }
        public long ID_HISTORICO { get; set; }
        public string PRODUTO_ID { get; set; }
        public Nullable<System.DateTime> DT_VIGENCIA { get; set; }
        public Nullable<decimal> VL_NOVOPRECO { get; set; }
        public decimal VL_PRECOANTERIOR { get; set; }
    
        public virtual EST_PRODUTO EST_PRODUTO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
    }
}
