//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_HISTORICO_LANCAMENTO
    {
        public long TENANT_ID { get; set; }
        public long ID_HISTORICO { get; set; }
        public long LANCAMENTOID { get; set; }
        public string TX_COMENTARIO { get; set; }
        public string TX_ACAO_EXECUTADA { get; set; }
        public System.DateTime DT_ENVIO { get; set; }
        public string USUARIOID { get; set; }
        public bool IS_ORIGEM_SISTEMA { get; set; }
    
        public virtual EST_LANCAMENTO EST_LANCAMENTO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
        public virtual INFRAUSUARIO INFRAUSUARIO { get; set; }
    }
}
