//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_CONTATO
    {
        public long ID { get; set; }
        public string PESSOA_ID { get; set; }
        public string TX_APELIDOCONTATO { get; set; }
        public string TX_EMAIL { get; set; }
        public string TX_TELEFONEFIXO { get; set; }
        public string TX_CELULAR { get; set; }
        public string TX_RAMAL { get; set; }
    
        public virtual EST_PESSOA EST_PESSOA { get; set; }
    }
}
