//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_PRODUTO_LANCTO
    {
        public long ID_PRODUTOLANCAMENTO { get; set; }
        public string PRODUTO_ID { get; set; }
        public long LANCAMENTO_ID { get; set; }
        public long QT_PRODUTO { get; set; }
        public System.DateTime DT_PEDIDO { get; set; }
        public decimal VL_TOTAL { get; set; }
    
        public virtual EST_LANCAMENTO EST_LANCAMENTO { get; set; }
        public virtual EST_PRODUTO EST_PRODUTO { get; set; }
    }
}
