//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_LANCAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_LANCAMENTO()
        {
            this.EST_ANEXO_LANCAMENTO = new HashSet<EST_ANEXO_LANCAMENTO>();
            this.EST_HISTORICO_LANCAMENTO = new HashSet<EST_HISTORICO_LANCAMENTO>();
            this.EST_PRODUTO_LANCTO = new HashSet<EST_PRODUTO_LANCTO>();
        }
    
        public long TENANT_ID { get; set; }
        public long ID { get; set; }
        public string TIPOLANCAMENTO_CD { get; set; }
        public string PESSOA_ID { get; set; }
        public string TX_CODIGOBARRAS { get; set; }
        public string SITUACAO_CD { get; set; }
        public Nullable<System.DateTime> DT_LANCAMENTO { get; set; }
        public Nullable<decimal> VL_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public string TX_DESCRICAO { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string ESTABELECIMENTOID { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<decimal> VL_IMPOSTO { get; set; }
        public System.DateTime DT_VENCIMENTO { get; set; }
        public string PESSOA_REMETENTE_ID { get; set; }
        public string PESSOA_DESTINATARIO_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ANEXO_LANCAMENTO> EST_ANEXO_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_HISTORICO_LANCAMENTO> EST_HISTORICO_LANCAMENTO { get; set; }
        public virtual INFRAESTABELECIMENTO INFRAESTABELECIMENTO { get; set; }
        public virtual EST_PESSOA EST_PESSOA { get; set; }
        public virtual EST_PESSOA EST_PESSOA1 { get; set; }
        public virtual EST_PESSOA EST_PESSOA2 { get; set; }
        public virtual EST_SITUACAOLANCAMENTO EST_SITUACAOLANCAMENTO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
        public virtual EST_TIPOLANCAMENTO EST_TIPOLANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_PRODUTO_LANCTO> EST_PRODUTO_LANCTO { get; set; }
    }
}
