//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESTAGIOEntities : DbContext
    {
        public ESTAGIOEntities()
            : base("name=ESTAGIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EST_ANEXO_LANCAMENTO> EST_ANEXO_LANCAMENTO { get; set; }
        public virtual DbSet<EST_CATEGORIAPRODUTO> EST_CATEGORIAPRODUTO { get; set; }
        public virtual DbSet<EST_CONTATO> EST_CONTATO { get; set; }
        public virtual DbSet<EST_ENDERECO> EST_ENDERECO { get; set; }
        public virtual DbSet<EST_HISTORICO_LANCAMENTO> EST_HISTORICO_LANCAMENTO { get; set; }
        public virtual DbSet<EST_HISTORICO_PRECO> EST_HISTORICO_PRECO { get; set; }
        public virtual DbSet<EST_LANCAMENTO> EST_LANCAMENTO { get; set; }
        public virtual DbSet<EST_LOG_AUDITORIA> EST_LOG_AUDITORIA { get; set; }
        public virtual DbSet<EST_PAPEL> EST_PAPEL { get; set; }
        public virtual DbSet<EST_PESSOA> EST_PESSOA { get; set; }
        public virtual DbSet<EST_PRODUTO> EST_PRODUTO { get; set; }
        public virtual DbSet<EST_PRODUTO_LANCTO> EST_PRODUTO_LANCTO { get; set; }
        public virtual DbSet<EST_SITUACAOLANCAMENTO> EST_SITUACAOLANCAMENTO { get; set; }
        public virtual DbSet<EST_TIPOENDERECO> EST_TIPOENDERECO { get; set; }
        public virtual DbSet<EST_TIPOLANCAMENTO> EST_TIPOLANCAMENTO { get; set; }
        public virtual DbSet<EST_TIPOPESSOA> EST_TIPOPESSOA { get; set; }
        public virtual DbSet<EST_UF> EST_UF { get; set; }
        public virtual DbSet<INFRAEMPRESA> INFRAEMPRESA { get; set; }
        public virtual DbSet<INFRAESTABELECIMENTO> INFRAESTABELECIMENTO { get; set; }
        public virtual DbSet<INFRAMNUMENU> INFRAMNUMENU { get; set; }
        public virtual DbSet<INFRAMNUMENUUSUARIO> INFRAMNUMENUUSUARIO { get; set; }
        public virtual DbSet<INFRAUSUARIO> INFRAUSUARIO { get; set; }
        public virtual DbSet<INFRAUSUARIOSENHASLOG> INFRAUSUARIOSENHASLOG { get; set; }
        public virtual DbSet<Loc_Aluguel> Loc_Aluguel { get; set; }
        public virtual DbSet<Loc_Cliente> Loc_Cliente { get; set; }
        public virtual DbSet<Loc_EnderecoCliente> Loc_EnderecoCliente { get; set; }
        public virtual DbSet<Loc_Funcionario> Loc_Funcionario { get; set; }
        public virtual DbSet<Loc_Marca> Loc_Marca { get; set; }
        public virtual DbSet<Loc_TipoVeiculo> Loc_TipoVeiculo { get; set; }
        public virtual DbSet<Loc_Veiculo> Loc_Veiculo { get; set; }
        public virtual DbSet<OSSYS_TENANT> OSSYS_TENANT { get; set; }
        public virtual DbSet<CRPGRUPO> CRPGRUPO { get; set; }
        public virtual DbSet<INFRAAUTHENTICATION> INFRAAUTHENTICATION { get; set; }
        public virtual DbSet<INFRAEMAILCFG> INFRAEMAILCFG { get; set; }
        public virtual DbSet<INFRAGRUPO> INFRAGRUPO { get; set; }
        public virtual DbSet<INFRAIN2FATYPE> INFRAIN2FATYPE { get; set; }
        public virtual DbSet<INFRAINAUTHTYPE> INFRAINAUTHTYPE { get; set; }
        public virtual DbSet<InfraLogRecupSenha> InfraLogRecupSenha { get; set; }
        public virtual DbSet<INFRASEGCONFIG> INFRASEGCONFIG { get; set; }
        public virtual DbSet<INFRAUSUARIO_IMG> INFRAUSUARIO_IMG { get; set; }
        public virtual DbSet<INFRAUSUARIOLOG1> INFRAUSUARIOLOG1 { get; set; }
    }
}
