//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAEMAILCFG
    {
        public int TENANT_ID { get; set; }
        public long ID { get; set; }
        public string SMTPSERVER { get; set; }
        public Nullable<int> SMTPPORT { get; set; }
        public Nullable<int> TIMEOUT { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string NOMEREMET { get; set; }
        public string EMAILADRESS { get; set; }
        public Nullable<bool> IS_SSL { get; set; }
        public Nullable<bool> IS_TLS { get; set; }
        public Nullable<bool> IS_AUTHENTICATED { get; set; }
        public Nullable<bool> CONFIRMLEIT { get; set; }
        public Nullable<bool> CONFIRMENTREG { get; set; }
        public string IMAPSERVER { get; set; }
        public Nullable<int> IMAPPORT { get; set; }
        public string INFRAESTABID { get; set; }
        public string PASSWORD_ANG { get; set; }
        public string URLSERVIDOR { get; set; }
    }
}
