//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAESTABELECIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFRAESTABELECIMENTO()
        {
            this.EST_LANCAMENTO = new HashSet<EST_LANCAMENTO>();
        }
    
        public int TENANT_ID { get; set; }
        public string ID { get; set; }
        public string NOMEEXIBICAO { get; set; }
        public string CODIGO { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string CNPJ { get; set; }
        public Nullable<bool> IS_MATRIZ { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string EMPRESAID { get; set; }
        public Nullable<int> IDIOMAID { get; set; }
        public string AVISOINICIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LANCAMENTO> EST_LANCAMENTO { get; set; }
        public virtual INFRAEMPRESA INFRAEMPRESA { get; set; }
    }
}
