//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAMNUMENUUSUARIO
    {
        public int TENANT_ID { get; set; }
        public long ID { get; set; }
        public string USUARIOID { get; set; }
        public Nullable<long> MENUID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual INFRAMNUMENU INFRAMNUMENU { get; set; }
        public virtual INFRAUSUARIO INFRAUSUARIO { get; set; }
    }
}
