//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRASEGCONFIG
    {
        public int TENANT_ID { get; set; }
        public long ID { get; set; }
        public Nullable<bool> IS_LETRASMAIUSCULAS { get; set; }
        public Nullable<bool> IS_NUMEROS { get; set; }
        public Nullable<bool> IS_CARACTERESESPECIAIS { get; set; }
        public Nullable<int> QTNINATIVIDADE { get; set; }
        public Nullable<int> QTNTROCASENHA { get; set; }
        public Nullable<int> QTNTENTATIVA { get; set; }
        public Nullable<int> QTNREPETICAO { get; set; }
        public Nullable<int> QTNMINIMA { get; set; }
        public Nullable<bool> IS_DROPSESSION { get; set; }
        public Nullable<int> LEVEL { get; set; }
    }
}
