//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAMNUMENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFRAMNUMENU()
        {
            this.INFRAMNUMENUUSUARIO = new HashSet<INFRAMNUMENUUSUARIO>();
        }
    
        public int TENANT_ID { get; set; }
        public long ID { get; set; }
        public string UNICOID { get; set; }
        public string LABEL { get; set; }
        public string LABEL_ENGLISH { get; set; }
        public string LABEL_SPANISH { get; set; }
        public string DESCRICAO { get; set; }
        public string DESCRICAO_ENGLISH { get; set; }
        public string DESCRICAO_SPANISH { get; set; }
        public Nullable<System.DateTime> DATACREATE { get; set; }
        public Nullable<int> ORDER { get; set; }
        public string CLASSICON { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public string URLDASHBOARD { get; set; }
        public string URL { get; set; }
        public string TxModuloCod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFRAMNUMENUUSUARIO> INFRAMNUMENUUSUARIO { get; set; }
    }
}
