//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFRAUSUARIO()
        {
            this.EST_ANEXO_LANCAMENTO = new HashSet<EST_ANEXO_LANCAMENTO>();
            this.EST_HISTORICO_LANCAMENTO = new HashSet<EST_HISTORICO_LANCAMENTO>();
            this.EST_LOG_AUDITORIA = new HashSet<EST_LOG_AUDITORIA>();
            this.INFRAMNUMENUUSUARIO = new HashSet<INFRAMNUMENUUSUARIO>();
            this.INFRAUSUARIOSENHASLOG = new HashSet<INFRAUSUARIOSENHASLOG>();
        }
    
        public Nullable<long> TENANT_ID { get; set; }
        public string ID { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string CARGO { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
        public Nullable<System.DateTime> DATAULTIMOACESSO { get; set; }
        public Nullable<bool> IS_BLOQUEADO { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> USEROUTSYSTEMSID { get; set; }
        public Nullable<int> IDIOMAID { get; set; }
        public Nullable<long> INFRACONFIGLDAP { get; set; }
        public string LASTLOGESTABID { get; set; }
        public string LASTLOGSPRINT { get; set; }
        public Nullable<bool> READLASTSPRINT { get; set; }
        public Nullable<bool> USAERP { get; set; }
        public Nullable<bool> FORCE_PSWCHANGE { get; set; }
        public Nullable<bool> USACHAT { get; set; }
        public string SENHAHASH512 { get; set; }
        public string TxCPF { get; set; }
        public Nullable<System.DateTime> DtHoraValidadeLogin { get; set; }
        public Nullable<bool> Is_Externo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ANEXO_LANCAMENTO> EST_ANEXO_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_HISTORICO_LANCAMENTO> EST_HISTORICO_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LOG_AUDITORIA> EST_LOG_AUDITORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFRAMNUMENUUSUARIO> INFRAMNUMENUUSUARIO { get; set; }
        public virtual OSSYS_TENANT OSSYS_TENANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFRAUSUARIOSENHASLOG> INFRAUSUARIOSENHASLOG { get; set; }
    }
}
