//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAAUTHENTICATION
    {
        public int TENANT_ID { get; set; }
        public long ID { get; set; }
        public Nullable<long> INFRAINAUTHTYPEID { get; set; }
        public Nullable<bool> IS_2FAENABLED { get; set; }
        public Nullable<long> INFRAIN2FATYPEID { get; set; }
    }
}
