//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFRAIN2FATYPE
    {
        public long ID { get; set; }
        public string NOME { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> ORDEM { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
