//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc_Aluguel
    {
        public long Id { get; set; }
        public long Loc_ClienteId { get; set; }
        public long Loc_FuncionarioId { get; set; }
        public long Loc_VeiculoId { get; set; }
        public System.DateTime DtRetirada { get; set; }
        public System.DateTime DtEntregaPrevista { get; set; }
        public System.DateTime DtEntregaEfetiva { get; set; }
        public Nullable<decimal> ValorPrevisto { get; set; }
        public decimal ValorFinal { get; set; }
        public Nullable<decimal> ValorMulta { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<bool> Is_Encerrado { get; set; }
    
        public virtual Loc_Cliente Loc_Cliente { get; set; }
        public virtual Loc_Funcionario Loc_Funcionario { get; set; }
        public virtual Loc_Veiculo Loc_Veiculo { get; set; }
    }
}
