//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loc_Veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loc_Veiculo()
        {
            this.Loc_Aluguel = new HashSet<Loc_Aluguel>();
        }
    
        public long Id { get; set; }
        public string Modelo { get; set; }
        public long MarcaId { get; set; }
        public int Ano { get; set; }
        public string Cor { get; set; }
        public string Placa { get; set; }
        public Nullable<int> Quilometragem { get; set; }
        public decimal ValorDiaria { get; set; }
        public Nullable<bool> Is_Disponivel { get; set; }
        public Nullable<long> TipoVeiculoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loc_Aluguel> Loc_Aluguel { get; set; }
        public virtual Loc_Marca Loc_Marca { get; set; }
        public virtual Loc_TipoVeiculo Loc_TipoVeiculo { get; set; }
    }
}
