//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkStudyDatabase.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSSYS_TENANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSSYS_TENANT()
        {
            this.EST_ANEXO_LANCAMENTO = new HashSet<EST_ANEXO_LANCAMENTO>();
            this.EST_HISTORICO_LANCAMENTO = new HashSet<EST_HISTORICO_LANCAMENTO>();
            this.EST_HISTORICO_PRECO = new HashSet<EST_HISTORICO_PRECO>();
            this.EST_LANCAMENTO = new HashSet<EST_LANCAMENTO>();
            this.EST_LOG_AUDITORIA = new HashSet<EST_LOG_AUDITORIA>();
            this.EST_PESSOA = new HashSet<EST_PESSOA>();
            this.EST_PRODUTO = new HashSet<EST_PRODUTO>();
            this.INFRAUSUARIO = new HashSet<INFRAUSUARIO>();
        }
    
        public string Name { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public long ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ANEXO_LANCAMENTO> EST_ANEXO_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_HISTORICO_LANCAMENTO> EST_HISTORICO_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_HISTORICO_PRECO> EST_HISTORICO_PRECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LANCAMENTO> EST_LANCAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LOG_AUDITORIA> EST_LOG_AUDITORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_PESSOA> EST_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_PRODUTO> EST_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFRAUSUARIO> INFRAUSUARIO { get; set; }
    }
}
